
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat May 26 13:30:44 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 31;
  public static final int CONST = 18;
  public static final int CHAR = 20;
  public static final int GREATER = 37;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 29;
  public static final int LESS = 39;
  public static final int MINUS = 12;
  public static final int RPAREN = 7;
  public static final int AND = 33;
  public static final int EQUALTO = 35;
  public static final int OR = 34;
  public static final int BOOL = 21;
  public static final int COMMA = 8;
  public static final int CLASS = 24;
  public static final int DIV = 42;
  public static final int PLUS = 11;
  public static final int LESSEQ = 40;
  public static final int IF = 16;
  public static final int DOT = 44;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 32;
  public static final int RETURN = 10;
  public static final int EQUAL = 13;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int MUL = 41;
  public static final int MOD = 43;
  public static final int NUMBER = 19;
  public static final int BREAK = 28;
  public static final int IDENT = 15;
  public static final int VOID = 14;
  public static final int LBRACE = 3;
  public static final int ELSE = 17;
  public static final int LSQUARE = 22;
  public static final int READ = 30;
  public static final int RSQUARE = 23;
  public static final int WHILE = 27;
  public static final int NOTEQUALTO = 36;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 25;
  public static final int PROG = 2;
  public static final int GREATEREQ = 38;
  public static final int PRINT = 9;
  public static final int DO = 26;
}

